/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyPolicyAppendixRouteImport } from './routes/privacy-policy-appendix'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as ForStoRouteImport } from './routes/for-sto'
import { Route as DiamondProtechRouteImport } from './routes/diamond-protech'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CarsOrderRouteImport } from './routes/cars-order'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicLeadsRouteImport } from './routes/api/public/leads'

const PrivacyPolicyAppendixRoute = PrivacyPolicyAppendixRouteImport.update({
  id: '/privacy-policy-appendix',
  path: '/privacy-policy-appendix',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const ForStoRoute = ForStoRouteImport.update({
  id: '/for-sto',
  path: '/for-sto',
  getParentRoute: () => rootRouteImport,
} as any)
const DiamondProtechRoute = DiamondProtechRouteImport.update({
  id: '/diamond-protech',
  path: '/diamond-protech',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsOrderRoute = CarsOrderRouteImport.update({
  id: '/cars-order',
  path: '/cars-order',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cars-order': typeof CarsOrderRoute
  '/contacts': typeof ContactsRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/diamond-protech': typeof DiamondProtechRoute
  '/for-sto': typeof ForStoRoute
  '/parts': typeof PartsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/privacy-policy-appendix': typeof PrivacyPolicyAppendixRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cars-order': typeof CarsOrderRoute
  '/contacts': typeof ContactsRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/diamond-protech': typeof DiamondProtechRoute
  '/for-sto': typeof ForStoRoute
  '/parts': typeof PartsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/privacy-policy-appendix': typeof PrivacyPolicyAppendixRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cars-order': typeof CarsOrderRoute
  '/contacts': typeof ContactsRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/diamond-protech': typeof DiamondProtechRoute
  '/for-sto': typeof ForStoRoute
  '/parts': typeof PartsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/privacy-policy-appendix': typeof PrivacyPolicyAppendixRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cars-order'
    | '/contacts'
    | '/cookie-policy'
    | '/diamond-protech'
    | '/for-sto'
    | '/parts'
    | '/privacy-policy'
    | '/privacy-policy-appendix'
    | '/api/public/leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/cars-order'
    | '/contacts'
    | '/cookie-policy'
    | '/diamond-protech'
    | '/for-sto'
    | '/parts'
    | '/privacy-policy'
    | '/privacy-policy-appendix'
    | '/api/public/leads'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cars-order'
    | '/contacts'
    | '/cookie-policy'
    | '/diamond-protech'
    | '/for-sto'
    | '/parts'
    | '/privacy-policy'
    | '/privacy-policy-appendix'
    | '/api/public/leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CarsOrderRoute: typeof CarsOrderRoute
  ContactsRoute: typeof ContactsRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DiamondProtechRoute: typeof DiamondProtechRoute
  ForStoRoute: typeof ForStoRoute
  PartsRoute: typeof PartsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PrivacyPolicyAppendixRoute: typeof PrivacyPolicyAppendixRoute
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy-policy-appendix': {
      id: '/privacy-policy-appendix'
      path: '/privacy-policy-appendix'
      fullPath: '/privacy-policy-appendix'
      preLoaderRoute: typeof PrivacyPolicyAppendixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-sto': {
      id: '/for-sto'
      path: '/for-sto'
      fullPath: '/for-sto'
      preLoaderRoute: typeof ForStoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diamond-protech': {
      id: '/diamond-protech'
      path: '/diamond-protech'
      fullPath: '/diamond-protech'
      preLoaderRoute: typeof DiamondProtechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars-order': {
      id: '/cars-order'
      path: '/cars-order'
      fullPath: '/cars-order'
      preLoaderRoute: typeof CarsOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CarsOrderRoute: CarsOrderRoute,
  ContactsRoute: ContactsRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DiamondProtechRoute: DiamondProtechRoute,
  ForStoRoute: ForStoRoute,
  PartsRoute: PartsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PrivacyPolicyAppendixRoute: PrivacyPolicyAppendixRoute,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
